### PR TITLE
Merge mappability snakemake 

### PR DESCRIPTION
**Pull request by cademirch**
Merging my snakemake rules for computing mappability

### CODE REVIEW

**Comment by tsackton** [comment]
@cademirch what is all the stuff in testgenome and testgenome2? If that is actual unit tests, great, but if it is just your testing it would be better to remove those files before merging. It looks at quick glance to me to just be testing to make sure things work, not unit tests, but let me know if I'm wrong.

**Comment by cademirch** [comment]
> @cademirch what is all the stuff in testgenome and testgenome2? If that is actual unit tests, great, but if it is just your testing it would be better to remove those files before merging. It looks at quick glance to me to just be testing to make sure things work, not unit tests, but let me know if I'm wrong.

Yes, I intended for everything in tests/ to be unit testing... but it turned out a little uglier than I planned. I just learned that snakemake has an option to generate unit tests. So I’ll go ahead and do that instead and push those tests in a bit.

**Comment by cademirch** [comment]
@tsackton I removed the tests directory, but have it locally so I can test any future changes. Let me know what you think.

**Comment by cademirch** [comment]
@tsackton Added a workflow for downloading reads, reading SRRs from a tsv with three fields (RunID, SM, LB), as per Russ's request. Russ also mentioned something about mapping and adding the read meta data to the mapping step. Not sure where the mapping rule/workflow is, could you point me to it?

**Comment by tsackton** [comment]
Merging this, but ultimately we'll want to move most or all of this code on to the production pipeline in https://github.com/harvardinformatics/shortRead_mapping_variantCalling. Need a roadmap there first though.

**Pull request merged**
